pos update + request endpoints
ProcessesHITS1/HitsInternsBackend pull request #32
Opened 2024-06-13 12:00 UTC by Ek128N

я запрещаю вам merg'ить

2024-06-18 08:32 UTC, ssslakter requested changes
Я не все смог посмотреть, но критические вещи написал.
Разберись еще с миграциями и форматированием плз.
Если это пока не смерджено, может проще одну миграцию для всего пр сделать.

2024-06-18 08:32 UTC, ssslakter commented on svc_InterviewBack/src/Models.cs
> +    public required string? Title { get; init; }
почему теперь можно создать позицию без тайтла?

2024-06-18 08:32 UTC, ssslakter commented on svc_InterviewBack/src/Controllers/PositionsController.cs
> +    public async Task<ActionResult> Update(Guid positionId, PositionUpdate positionData)
пусть объект тоже называется `positionUpdate`

2024-06-18 08:32 UTC, ssslakter commented on svc_InterviewBack/src/Models.cs
> +    public int?  NSeats { get; init; }
переместить к моделькам позиций

2024-06-18 08:32 UTC, ssslakter commented on svc_InterviewBack/src/Models.cs
> +    public required string? Title { get; init; }
и давай тогда переименуем в `PositionCreation` чтобы матчилось с апдейтом

2024-06-18 08:32 UTC, ssslakter commented on svc_InterviewBack/src/Models.cs
> +    public int?  NSeats { get; init; }
required не нужен ведь

2024-06-18 08:32 UTC, ssslakter commented on svc_InterviewBack/src/Controllers/PositionsController.cs
> +    public async Task<ActionResult> Update(Guid positionId, PositionUpdate positionData)
добавить сигнатуру модельки, как при создании

2024-06-18 08:32 UTC, ssslakter commented on svc_InterviewBack/src/Services/PositionsService.cs
> +
Давай лучше примерно так сделаем, красивее будет

```cs
public static class EntityExtensions
{
    public static void UpdateProperties<T>(this T entity, T updateData) where T : class
    {
        var properties = typeof(T).GetProperties();
        foreach (var property in properties)
        {
            var newValue = property.GetValue(updateData);
            if (newValue != null)
            {
                property.SetValue(entity, newValue);
            }
        }
    }
}
```
В сервисе
```cs
public async Task<PositionInfo> Update(Guid positionId, PositionUpdate positionData)
{
    var positionEntity = await context.Positions.FindAsync(positionId);
    if (positionEntity == null) throw new NotFoundException($"Position {positionId} not found");

    positionEntity.UpdateProperties(positionData);

    await context.SaveChangesAsync();
    return mapper.Map<PositionInfo>(positionEntity);
}

```

2024-06-18 08:32 UTC, ssslakter commented on svc_InterviewBack/src/Controllers/RequestController.cs
> +    public async Task<ActionResult> CreateRequestStatusInSeason(int year, string statusName)
удалить нельзя?

2024-06-18 08:32 UTC, ssslakter commented on svc_InterviewBack/src/Services/RequestService.cs
> +    Task<RequestDetails> CreateAsync(Guid studentId, Guid positionId, string statusName);
тут как-бы все асинк, а названо асинк только это

2024-06-18 08:32 UTC, ssslakter commented on svc_InterviewBack/src/Controllers/RequestController.cs
> +        [FromQuery(Name = "requests")] List<Guid>? requestIds,
в чем смысл получать несколько реквестов по их айдишникам?

2024-06-18 08:32 UTC, ssslakter commented on svc_InterviewBack/src/Controllers/RequestController.cs
> +    public async Task<ActionResult> GetRequests(
сигнатура моделек

2024-06-18 08:32 UTC, ssslakter commented on svc_InterviewBack/src/Controllers/RequestController.cs
> +        [FromQuery(Name = "requests")] List<Guid>? requestIds,
опять, что за requestIds, какой юзкейс, когда студент выбирает какие-то реквесты по их айди

2024-06-18 08:32 UTC, ssslakter commented on svc_InterviewBack/src/Controllers/RequestController.cs
> +        [FromQuery(Name = "requests")] List<Guid>? requestIds,
студенту по идее важно получить текущий статус, либо посмотреть историю по статусам в рамках позиции на которую он подает

2024-06-18 08:32 UTC, ssslakter commented on svc_InterviewBack/src/Controllers/RequestController.cs
> +    [HttpPost("position/{positionId}/status/{statusName}")] //student role
документация

2024-06-18 08:32 UTC, ssslakter commented on svc_InterviewBack/src/Controllers/RequestController.cs
> +    public async Task<ActionResult<RequestDetails>> Create(Guid positionId,string statusName)
почему пользователь выбирает статус, с которым создается реквест. Он просто создает запрос на позицию, а сервис сам ставит ему дефолтный статус и возвращает дтошку

2024-06-18 08:32 UTC, ssslakter commented on svc_InterviewBack/src/Models.cs
> +    public ResultStatus? ResultStatus { get; init; }
статус не может быть никаким

2024-06-18 08:32 UTC, ssslakter commented on svc_InterviewBack/src/Models.cs
> +public record RequestStatusSnapshotData
хмм, как будто в истории было бы логично показывать не только изменения статусов, но и сообщения которые по ним приходят

2024-06-18 08:32 UTC, ssslakter commented on svc_InterviewBack/src/Program.cs
> +
не думаю что нужно добавлять лишнюю зависимость.
Тут написано как сделать строки в енамах в сваггере
https://github.com/domaindrivendev/Swashbuckle.WebApi/blob/e2fa027dfb9652304e13d68f9ca06a2be0b4296f/README.md#describeallenumsasstrings
Здесь просто про system.json
https://learn.microsoft.com/ru-ru/dotnet/api/system.text.json.serialization.jsonstringenumconverter?view=net-8.0

2024-06-18 08:32 UTC, ssslakter commented on svc_InterviewBack/src/Program.cs
> +        c.UseOneOfForPolymorphism();
wtf

2024-06-18 08:32 UTC, ssslakter commented on svc_InterviewBack/src/Data/DbModels.cs
> +    public List<RequestStatusTemplate>? RequestStatuses { get; set; }
переименуй в `RequestStatusTemplates`, лучше звучит и смысл передает

2024-06-18 08:32 UTC, ssslakter commented on svc_InterviewBack/src/Data/DbModels.cs
> +    public List<RequestStatusTemplate>? RequestStatuses { get; set; }
и опять почему налабл

2024-06-18 08:32 UTC, ssslakter commented on svc_InterviewBack/src/Data/DbModels.cs
> +    public List<RequestStatusTemplate>? RequestStatuses { get; set; }
сезон может быть сезон без статусов? и даже если так, то лучше иметь пустой список, чем проверять на нулл каждый раз

2024-06-18 08:32 UTC, ssslakter commented on svc_InterviewBack/src/Data/DbModels.cs
> -    public RequestStatus Status { get; init; } = RequestStatus.Pending;
как определяется текущий статус? последний элемент в списке снапшотов? можно явно сделать это свойство с геттером, и сделать чтобы геттер получал последний элемент

2024-06-18 08:32 UTC, ssslakter commented on svc_InterviewBack/src/Data/DbModels.cs
> +    public RequestResult? RequestResult { get; set; }
опять налл, почему?

2024-06-18 08:32 UTC, ssslakter commented on svc_InterviewBack/src/Data/DbModels.cs
> +public class RequestStatusSnapshot
внезапно рекорды стали классами

2024-06-18 08:32 UTC, ssslakter commented on svc_InterviewBack/src/Migrations/20240606070048_PositionsUpdate.cs
пустая миграция

2024-06-18 08:32 UTC, ssslakter commented on svc_InterviewBack/src/Migrations/20240607093231_HistoryRequest2.cs
еще одна

2024-06-18 08:32 UTC, ssslakter commented on svc_InterviewBack/src/Data/DbModels.cs
> +public class RequestStatusTemplate
у тебя получается сезон к темплейту один ко многим, то есть если я создам темплейт с названием "done", я смогу его использовать только в одном сезоне и больше нигде. Это неправильно

2024-06-18 08:32 UTC, ssslakter commented on svc_InterviewBack/src/Services/RequestService.cs
> +            }
давай без такого

2024-06-18 08:32 UTC, ssslakter commented on svc_InterviewBack/src/Services/RequestService.cs
> +        }
чтобы вот так с бубном не танцевать, проще иметь в шаблоне статус, который используется при создании реквеста, его и указывать

2024-06-18 08:32 UTC, ssslakter commented on svc_InterviewBack/src/Services/RequestService.cs
> +        interviewRequest.RequestStatusSnapshots.Add(newSnapshot);
кажется всю логику со снапшотами стоит вынести в спомогательный класс и вызывать методы, чтобы оно в логике основной не мешалось

2024-06-18 08:32 UTC, ssslakter commented on svc_InterviewBack/src/Services/RequestService.cs
> +            .FirstOrDefaultAsync(r => r.Id == requestId);
💀

2024-06-18 08:32 UTC, ssslakter commented on svc_InterviewBack/src/Services/RequestService.cs
> +    public async Task<RequestDetails> UpdateRequestStatus(Guid requestId, string newRequestStatus)
опять выглядит как танцы с бубном.
Исправить очень просто:
- добавить нормальные айдишники в шаблон статуса
- на клиенте пользователь будет не подбирать строки, а выбирать из статусов, которые пришли для данного сезона, поэтому в модельке приходит айдишник
- на бэке проверяем, что в сезоне есть этот статус, это можно сделать отдельно от запроса в бд на реквест, тогда не будет кучи джоинов. Либо прямо в модельке шаблона реквеста храним айди сезона
- меняем статус

2024-06-18 09:03 UTC, Ek128N commented on svc_InterviewBack/src/Services/PositionsService.cs
> +
как нормально задать соответствие между Position и PositionUpdate

2024-06-18 09:05 UTC, Ek128N commented on svc_InterviewBack/src/Controllers/RequestController.cs
> +    public async Task<ActionResult> CreateRequestStatusInSeason(int year, string statusName)
в теории - можно сделать так что, если статус - не привязан  к request'у, то можно удалить

2024-06-18 09:09 UTC, Ek128N commented on svc_InterviewBack/src/Controllers/RequestController.cs
> +        [FromQuery(Name = "requests")] List<Guid>? requestIds,
например расширеную информацию(includeHistory) по конкретному(ым) запросу(ам)

2024-06-18 09:29 UTC, Ek128N commented on svc_InterviewBack/src/Controllers/RequestController.cs
> +    [HttpPost("position/{positionId}/status/{statusName}")] //student role
зачем

2024-06-18 10:03 UTC, Ek128N commented on svc_InterviewBack/src/Controllers/RequestController.cs
> +    public async Task<ActionResult<RequestDetails>> Create(Guid positionId,string statusName)
потому что мы решили, что нет дефолтных статусов, статусы привязаны к сезону и сначало надо статус создать

2024-06-18 10:38 UTC, Ek128N commented on svc_InterviewBack/src/Data/DbModels.cs
> +public class RequestStatusSnapshot
привычка)

2024-06-18 10:50 UTC, furlupe commented on svc_InterviewBack/src/Controllers/RequestController.cs
> +    public async Task<ActionResult> GetRequests(
немного не пон что Слава имел в виду под сигнатурой моделек, но сюда надо засунуть возвращаемый методом тип (Task<ActionResult<T>>), иначе в сваггере потом не будет норм доки => не выйдет сгенерить хттп-клиент на фронте

2024-06-18 11:00 UTC, Ek128N commented on svc_InterviewBack/src/Controllers/RequestController.cs
> +    public async Task<ActionResult> GetRequests(
ну это вроде и есть сигнатурка
Task<ActionResult<PaginatedItems<RequestData>>>

2024-06-18 11:01 UTC, furlupe commented on svc_InterviewBack/src/Controllers/RequestController.cs
> +        [FromQuery(Name = "requests")] List<Guid>? requestIds,
ревестИд не нужен тут вообще, он же все СВОИ получает

2024-06-18 11:01 UTC, furlupe commented on svc_InterviewBack/src/Controllers/RequestController.cs
> +    public async Task<ActionResult> GetStudentRequests(
для всех гетов нужен возвращаемый тип, иначе сваггер и все такое будет кривой - писал ранее, далее так же

2024-06-18 11:01 UTC, furlupe commented on svc_InterviewBack/src/Controllers/RequestController.cs
> +    [HttpGet("student")]
"my" тогда уж? ведь студент свои получить хочет, а /request/student относительно самого студента чет не оч RESTful

2024-06-18 11:01 UTC, furlupe commented on svc_InterviewBack/src/Data/DbModels.cs
> +    public RequestResult? RequestResult { get; set; }
надо тогда по-дефолту его Pending объявить, точнее, дать дефолтный объект с пендингом

2024-06-18 11:01 UTC, furlupe commented on svc_InterviewBack/src/Migrations/20240606070048_PositionsUpdate.cs
к чему тут пустая миграция?

2024-06-18 11:01 UTC, furlupe commented on svc_InterviewBack/src/Migrations/20240607093231_HistoryRequest2.cs
аналогично, почему?

2024-06-18 11:01 UTC, furlupe commented on svc_InterviewBack/src/Program.cs
> +
вынесите это в либу вообще, я мб в чаты у себя че засуну

2024-06-18 11:01 UTC, furlupe commented on svc_InterviewBack/src/Program.cs
> +
расширением для builder'а оформите

2024-06-18 11:11 UTC, Ek128N commented on svc_InterviewBack/src/Models.cs
> +public record RequestStatusSnapshotData
Что за сообщения, если ты про RequestResult, то решили, что истории description не будет

2024-06-18 15:51 UTC, ssslakter commented on svc_InterviewBack/src/Controllers/RequestController.cs
> +    [HttpPost("position/{positionId}/status/{statusName}")] //student role
потому что в остальных местах есть

2024-06-18 15:52 UTC, ssslakter commented on svc_InterviewBack/src/Models.cs
> +public record RequestStatusSnapshotData
а в чем смысл этой истории тогда

2024-06-18 15:52 UTC, ssslakter commented on svc_InterviewBack/src/Models.cs
> +public record RequestStatusSnapshotData
@furlupe чекни код тут тоже

2024-06-18 16:05 UTC, furlupe commented on svc_InterviewBack/src/Models.cs
> +public record RequestStatusSnapshotData
этож история статусов, емнип, мб и стоит дескрипш добавить опциональный

2024-06-18 16:06 UTC, furlupe commented on svc_InterviewBack/src/Models.cs
> +public record RequestStatusSnapshotData
то есть, пускай у студента будет такая возможность, чтобы к реквесту можно было добавить описание, лишним не будет, делать не сложно

не помню правла чтобы мы обсуждали описание это

2024-06-18 16:09 UTC, furlupe commented on svc_InterviewBack/src/Models.cs
> +public record RequestStatusSnapshotData
ага теперь вижу, в снапшоте нет описания
в целом, особо не важно, если лень - можно не делать

2024-06-20 06:33 UTC, Ek128N commented on svc_InterviewBack/src/Data/DbModels.cs
> +    public RequestResult? RequestResult { get; set; }
решили, что default'ный - null

2024-06-20 07:17 UTC, Ek128N commented on svc_InterviewBack/src/Program.cs
> +        c.UseOneOfForPolymorphism();
❓

2024-06-20 07:42 UTC, Ek128N commented on svc_InterviewBack/src/Program.cs
> +
для IserviceCollection сделал, а не для builder'a

2024-06-20 10:48 UTC, ssslakter approved these changes

2024-06-20 10:49 UTC, merged